baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CAP Biblio'
theme = 'hugo-universal-theme'
[languages]
  [languages.en]
    contentDir = 'content/english'
    languageName = 'English'
    weight = 10
  [languages.fr]
    contentDir = 'content/french'
    languageName = 'Français'
    weight = 20
[params]
    disabled_logo = false
    logo_text = "CAP Biblio"

    logo = "img/Logo.jpg"