baseURL = 'https://example.org/'
languageCode = 'fr'
title = 'CAP Biblio'
theme = 'ananke'
defaultContentLanguage = "fr"
[languages]
  [languages.en]
    contentDir = 'content/english'
    languageName = 'English'
    weight = 10
  [languages.fr]
    contentDir = 'content/french'
    languageName = 'Français'
    weight = 20
[params]
    site_logo = "img/logo_small.jpg"
[markup.goldmark.renderer]
    unsafe = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'